### ISSUE TITLE
Map canvas shrinks to half width of column in mobile view

### ISSUE THREAD

**Issue by clavis-magna** [thea-jpg/initial-map-test#4]
See image - in mobile view the map should fill the width of the stacked column. instead it is half width. This is probably something in the map css competing with the responsive css?

![image](https://user-images.githubusercontent.com/2109125/84224986-582f8080-ab21-11ea-8cf9-10267e0d2dbe.png)

**Comment by thea-jpg** [comment]
resolved by using iframe in #7  #c26a791, the map now always fits to the size of the column it is within.

![image](https://user-images.githubusercontent.com/66339564/84348256-dbbba100-abf7-11ea-9686-38b173ebc6bc.png)
